
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import ENV from '@/config/env';

// Check for required Supabase configuration
if (!ENV.SUPABASE_URL || !ENV.SUPABASE_ANON_KEY) {
  console.error('Missing required Supabase configuration. Please check your environment variables.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  ENV.SUPABASE_URL || '', // Fallback to empty string to prevent runtime errors
  ENV.SUPABASE_ANON_KEY || '' // Fallback to empty string to prevent runtime errors
);
